import type { Grant, TeamMember, ActionItem, Anomaly, Stage } from "./types"

export const team: TeamMember[] = [
  { id: "maria", name: "Maria Chen", initials: "MC", role: "Grants Manager", load: 142, color: "#5A56B3" },
  { id: "laurie", name: "Laurie Park", initials: "LP", role: "Research Lead", load: 64, color: "#10B981" },
  { id: "grace", name: "Grace Okafor", initials: "GO", role: "Writer", load: 88, color: "#F59E0B" },
  { id: "nina", name: "Nina Alvarez", initials: "NA", role: "Programs Lead", load: 71, color: "#06B6D4" },
  { id: "james", name: "James Wu", initials: "JW", role: "ED", load: 38, color: "#0F3E17" },
]

export const stageOrder: Stage[] = [
  "Researching",
  "Planned",
  "LOI In Progress",
  "LOI Submitted",
  "Application In Progress",
  "Application Submitted",
  "Awarded - Active",
  "Closed",
  "Declined",
]

export const grants: Grant[] = [
  {
    id: "G-2024-118",
    title: "Diabetes Prevention Program · Year 2",
    funder: "HHS / HRSA",
    funderType: "Federal",
    stage: "Awarded - Active",
    nextAction: "Q2 drawdown package",
    deadline: "2026-05-15",
    daysToDeadline: 14,
    award: 487500,
    weighted: 487500,
    ownerId: "maria",
    cycle: "Y2",
    fundingSource: "HRSA-23-104",
    cfda: "93.426",
    fain: "U58DP007214",
    period: "09/01/24 — 08/31/25",
    indirect: 0.155,
    matchRequired: true,
    lastUpdated: "2 hours ago",
    projectGroup: "Health Equity",
    priority: "P0",
    renewalLikelihood: "High",
  },
  {
    id: "G-2025-042",
    title: "Community Health Workers Initiative",
    funder: "Robert Wood Johnson Foundation",
    funderType: "Private",
    stage: "LOI In Progress",
    nextAction: "Finalize LOI narrative",
    deadline: "2026-05-08",
    daysToDeadline: 7,
    award: 250000,
    weighted: 87500,
    ownerId: "grace",
    cycle: "2025",
    fundingSource: "Pioneering Ideas",
    period: "01/01/26 — 12/31/27",
    lastUpdated: "yesterday",
    projectGroup: "Workforce",
    priority: "P1",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-043",
    title: "General Operating Support · 2025",
    funder: "Hartford Foundation",
    funderType: "Private",
    stage: "LOI In Progress",
    nextAction: "Send LOI to Hartford PO",
    deadline: "2026-05-12",
    daysToDeadline: 11,
    award: 150000,
    weighted: 67500,
    ownerId: "maria",
    cycle: "2025",
    fundingSource: "Greater Hartford Grants",
    period: "07/01/25 — 06/30/26",
    lastUpdated: "3 hours ago",
    projectGroup: "General Op",
    priority: "P1",
    renewalLikelihood: "High",
  },
  {
    id: "G-2025-044",
    title: "Skoll Award · Systems Change Cohort",
    funder: "Skoll Foundation",
    funderType: "Private",
    stage: "Researching",
    nextAction: "Warm intro from board chair",
    deadline: "2026-06-30",
    daysToDeadline: 60,
    award: 1250000,
    weighted: 125000,
    ownerId: "nina",
    cycle: "2025",
    fundingSource: "Open Call",
    lastUpdated: "5 days ago",
    projectGroup: "Health Equity",
    priority: "P2",
    renewalLikelihood: "Unknown",
  },
  {
    id: "G-2025-045",
    title: "Workforce Capacity Grant · Cohort 3",
    funder: "Cummings Foundation",
    funderType: "Private",
    stage: "LOI In Progress",
    nextAction: "Reassign — Maria over capacity",
    deadline: "2026-05-20",
    daysToDeadline: 19,
    award: 100000,
    weighted: 35000,
    ownerId: "maria",
    cycle: "2025",
    fundingSource: "$100K for 100 grants",
    period: "10/01/25 — 09/30/26",
    lastUpdated: "1 day ago",
    projectGroup: "Workforce",
    priority: "P2",
    renewalLikelihood: "Low",
    flagged: true,
  },
  {
    id: "G-2025-046",
    title: "Rural Health Telehealth Expansion",
    funder: "USDA Rural Development",
    funderType: "Federal",
    stage: "Application In Progress",
    nextAction: "Budget narrative draft",
    deadline: "2026-05-30",
    daysToDeadline: 29,
    award: 425000,
    weighted: 233750,
    ownerId: "laurie",
    cycle: "FY26",
    fundingSource: "RHCD-26-001",
    cfda: "10.855",
    period: "10/01/26 — 09/30/29",
    indirect: 0.1,
    matchRequired: true,
    lastUpdated: "today",
    projectGroup: "Health Equity",
    priority: "P1",
    renewalLikelihood: "Unknown",
  },
  {
    id: "G-2025-047",
    title: "Mental Health First Aid Training",
    funder: "SAMHSA",
    funderType: "Federal",
    stage: "Application In Progress",
    nextAction: "Logic model review",
    deadline: "2026-06-05",
    daysToDeadline: 35,
    award: 320000,
    weighted: 176000,
    ownerId: "grace",
    cycle: "FY26",
    fundingSource: "SM-26-014",
    cfda: "93.243",
    period: "09/30/26 — 09/29/29",
    matchRequired: false,
    lastUpdated: "4 hours ago",
    projectGroup: "Capacity",
    priority: "P1",
    renewalLikelihood: "Medium",
    blocked: true,
    blockedReason: "Awaiting CFO budget sign-off",
  },
  {
    id: "G-2025-048",
    title: "Youth Substance Use Prevention",
    funder: "Conrad Hilton Foundation",
    funderType: "Private",
    stage: "Application In Progress",
    nextAction: "Outcomes framework",
    deadline: "2026-06-10",
    daysToDeadline: 40,
    award: 200000,
    weighted: 110000,
    ownerId: "nina",
    cycle: "2026",
    fundingSource: "Catholic Sisters Initiative",
    lastUpdated: "yesterday",
    projectGroup: "Health Equity",
    priority: "P2",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-049",
    title: "Data Infrastructure Modernization",
    funder: "Kresge Foundation",
    funderType: "Private",
    stage: "Application In Progress",
    nextAction: "Tech narrative + vendor quotes",
    deadline: "2026-05-25",
    daysToDeadline: 24,
    award: 350000,
    weighted: 192500,
    ownerId: "maria",
    cycle: "2026",
    fundingSource: "Human Services Program",
    lastUpdated: "6 days ago",
    projectGroup: "Capacity",
    priority: "P2",
    renewalLikelihood: "Low",
    flagged: true,
  },
  {
    id: "G-2025-050",
    title: "Healthcare Access Fellowship",
    funder: "Kellogg Foundation",
    funderType: "Private",
    stage: "Application In Progress",
    nextAction: "Letters of support",
    deadline: "2026-06-15",
    daysToDeadline: 45,
    award: 175000,
    weighted: 96250,
    ownerId: "laurie",
    cycle: "2026",
    fundingSource: "Racial Equity Program",
    lastUpdated: "today",
    projectGroup: "Workforce",
    priority: "P3",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-051",
    title: "Maternal Health Outcomes Research",
    funder: "NIH / NICHD",
    funderType: "Federal",
    stage: "Application Submitted",
    nextAction: "Awaiting study section review",
    deadline: "2026-08-01",
    daysToDeadline: 90,
    award: 740000,
    weighted: 296000,
    ownerId: "laurie",
    cycle: "FY26",
    fundingSource: "R01 Mechanism",
    cfda: "93.865",
    period: "12/01/26 — 11/30/29",
    matchRequired: false,
    lastUpdated: "2 weeks ago",
    projectGroup: "Research",
    priority: "P2",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-052",
    title: "Community Mental Health Block Grant",
    funder: "CT Dept of Health",
    funderType: "State",
    stage: "Application Submitted",
    nextAction: "Site visit scheduled",
    deadline: "2026-06-20",
    daysToDeadline: 50,
    award: 215000,
    weighted: 86000,
    ownerId: "nina",
    cycle: "FY26",
    fundingSource: "MHBG Pass-through",
    period: "07/01/26 — 06/30/27",
    lastUpdated: "1 week ago",
    projectGroup: "Health Equity",
    priority: "P3",
    renewalLikelihood: "High",
  },
  {
    id: "G-2024-088",
    title: "School-Based Health Centers · Year 3",
    funder: "HHS / HRSA",
    funderType: "Federal",
    stage: "Awarded - Active",
    nextAction: "Mid-year progress report",
    deadline: "2026-05-31",
    daysToDeadline: 30,
    award: 612000,
    weighted: 612000,
    ownerId: "maria",
    cycle: "Y3",
    fundingSource: "HRSA-22-088",
    cfda: "93.224",
    fain: "H80CS00214",
    period: "06/01/24 — 05/31/25",
    indirect: 0.155,
    matchRequired: true,
    lastUpdated: "today",
    projectGroup: "Health Equity",
    priority: "P0",
    renewalLikelihood: "High",
  },
  {
    id: "G-2024-091",
    title: "Health Equity Innovation Fund",
    funder: "California Endowment",
    funderType: "Private",
    stage: "Awarded - Active",
    nextAction: "Q1 narrative report",
    deadline: "2026-05-20",
    daysToDeadline: 19,
    award: 300000,
    weighted: 300000,
    ownerId: "grace",
    cycle: "Y1",
    fundingSource: "Building Healthy Communities",
    period: "04/01/25 — 03/31/26",
    lastUpdated: "yesterday",
    projectGroup: "Health Equity",
    priority: "P1",
    renewalLikelihood: "High",
    flagged: true,
  },
  {
    id: "G-2024-095",
    title: "Workforce Training Pipeline",
    funder: "Department of Labor",
    funderType: "Federal",
    stage: "Awarded - Active",
    nextAction: "PMS drawdown",
    deadline: "2026-06-01",
    daysToDeadline: 31,
    award: 540000,
    weighted: 540000,
    ownerId: "james",
    cycle: "Y1",
    fundingSource: "WIOA Grant",
    cfda: "17.258",
    fain: "DOL-2024-WIOA-0042",
    period: "07/01/24 — 06/30/26",
    indirect: 0.12,
    matchRequired: true,
    lastUpdated: "3 days ago",
    projectGroup: "Workforce",
    priority: "P0",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-053",
    title: "Community Resilience Initiative",
    funder: "MacArthur Foundation",
    funderType: "Private",
    stage: "Researching",
    nextAction: "Review eligibility criteria",
    deadline: "2026-07-15",
    daysToDeadline: 75,
    award: 600000,
    weighted: 60000,
    ownerId: "laurie",
    cycle: "2026",
    fundingSource: "100&Change",
    lastUpdated: "today",
    projectGroup: "Health Equity",
    priority: "P3",
    renewalLikelihood: "Unknown",
  },
  {
    id: "G-2025-054",
    title: "Digital Health Equity Toolkit",
    funder: "Walton Family Foundation",
    funderType: "Private",
    stage: "Researching",
    nextAction: "Concept memo",
    deadline: "2026-08-30",
    daysToDeadline: 120,
    award: 225000,
    weighted: 22500,
    ownerId: "grace",
    cycle: "2026",
    fundingSource: "Education / K-12",
    lastUpdated: "1 week ago",
    projectGroup: "Capacity",
    priority: "P3",
    renewalLikelihood: "Unknown",
  },
  {
    id: "G-2024-076",
    title: "Behavioral Health Integration · Y2",
    funder: "BCBS Foundation",
    funderType: "Corporate",
    stage: "Awarded - Active",
    nextAction: "Annual report",
    deadline: "2026-07-01",
    daysToDeadline: 60,
    award: 175000,
    weighted: 175000,
    ownerId: "nina",
    cycle: "Y2",
    fundingSource: "Health Equity Program",
    period: "07/01/24 — 06/30/26",
    lastUpdated: "5 days ago",
    projectGroup: "Health Equity",
    priority: "P2",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-055",
    title: "Telehealth Equipment Upgrade",
    funder: "Verizon Foundation",
    funderType: "Corporate",
    stage: "Planned",
    nextAction: "Decide on go/no-go",
    deadline: "2026-06-25",
    daysToDeadline: 55,
    award: 75000,
    weighted: 18750,
    ownerId: "james",
    cycle: "2026",
    fundingSource: "Digital Inclusion",
    lastUpdated: "yesterday",
    projectGroup: "Capacity",
    priority: "P3",
    renewalLikelihood: "Low",
  },
  {
    id: "G-2025-056",
    title: "Substance Use Recovery Pilot",
    funder: "City of Hartford",
    funderType: "Local",
    stage: "LOI In Progress",
    nextAction: "Coordinate with city liaison",
    deadline: "2026-05-18",
    daysToDeadline: 17,
    award: 50000,
    weighted: 22500,
    ownerId: "nina",
    cycle: "FY26",
    fundingSource: "ARPA Set-aside",
    period: "07/01/26 — 06/30/27",
    lastUpdated: "today",
    projectGroup: "Health Equity",
    priority: "P2",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-057",
    title: "Youth Leadership Development",
    funder: "United Way of CT",
    funderType: "Private",
    stage: "Application Submitted",
    nextAction: "Awaiting decision",
    deadline: "2026-07-30",
    daysToDeadline: 90,
    award: 85000,
    weighted: 38250,
    ownerId: "grace",
    cycle: "2026",
    fundingSource: "Community Impact Fund",
    period: "01/01/27 — 12/31/27",
    lastUpdated: "2 weeks ago",
    projectGroup: "Workforce",
    priority: "P3",
    renewalLikelihood: "Medium",
  },
]

export const actionQueue: ActionItem[] = [
  {
    id: "a1",
    title: "Send LOI to Hartford PO",
    detail: "Final review complete. Push from Maria's drafts.",
    grantTitle: "General Operating Support · 2025",
    grantId: "G-2025-043",
    stage: "LOI In Progress",
    due: "Today, 5pm",
    daysOut: 0,
    award: 150000,
    ownerId: "maria",
  },
  {
    id: "a2",
    title: "Q2 drawdown package — DPP Y2",
    detail: "Package $112K for personnel + indirect. Cutoff Friday.",
    grantTitle: "Diabetes Prevention Program · Y2",
    grantId: "G-2024-118",
    stage: "Awarded - Active",
    due: "Fri",
    daysOut: 3,
    award: 112000,
    ownerId: "maria",
  },
  {
    id: "a3",
    title: "Reassign Cummings LOI",
    detail: "Maria 142% load. Recommend Grace.",
    grantTitle: "Workforce Capacity Grant",
    grantId: "G-2025-045",
    stage: "LOI In Progress",
    due: "Today",
    daysOut: 0,
    award: 100000,
    ownerId: "maria",
  },
  {
    id: "a4",
    title: "Q1 narrative report — CA Endowment",
    detail: "Outcomes data from programs ready. Maria writes.",
    grantTitle: "Health Equity Innovation Fund",
    grantId: "G-2024-091",
    stage: "Awarded - Active",
    due: "May 20",
    daysOut: 19,
    award: 300000,
    ownerId: "grace",
  },
  {
    id: "a5",
    title: "Unblock SAMHSA logic model",
    detail: "CFO sign-off pending — ping James.",
    grantTitle: "Mental Health First Aid Training",
    grantId: "G-2025-047",
    stage: "Application In Progress",
    due: "Tue",
    daysOut: 1,
    award: 320000,
    ownerId: "grace",
  },
  {
    id: "a6",
    title: "Mid-year report — SBHC Y3",
    detail: "Pull enrollment + utilization from Epic.",
    grantTitle: "School-Based Health Centers · Y3",
    grantId: "G-2024-088",
    stage: "Awarded - Active",
    due: "May 31",
    daysOut: 30,
    award: 612000,
    ownerId: "maria",
  },
  {
    id: "a7",
    title: "Follow up with Kresge PO",
    detail: "Silent for 9 days — last touchpoint Apr 22.",
    grantTitle: "Data Infrastructure Modernization",
    grantId: "G-2025-049",
    stage: "Application In Progress",
    due: "This week",
    daysOut: 4,
    award: 350000,
    ownerId: "maria",
  },
  {
    id: "a8",
    title: "Budget narrative — USDA RHCD",
    detail: "Match commitment letter from board chair.",
    grantTitle: "Rural Health Telehealth Expansion",
    grantId: "G-2025-046",
    stage: "Application In Progress",
    due: "May 30",
    daysOut: 29,
    award: 425000,
    ownerId: "laurie",
  },
  {
    id: "a9",
    title: "Skoll warm intro",
    detail: "Board chair connecting with Skoll team.",
    grantTitle: "Skoll Award · Systems Change",
    grantId: "G-2025-044",
    stage: "Researching",
    due: "Next week",
    daysOut: 8,
    award: 1250000,
    ownerId: "nina",
  },
]

export const anomalies: Anomaly[] = [
  {
    id: "an1",
    level: "crit",
    title: "Hartford burn 18% over plan",
    body: "DPP Y2 personnel spend is tracking 18% ahead of plan through Q2 — risks running out before Sept.",
    cta: "Investigate",
  },
  {
    id: "an2",
    level: "warn",
    title: "Kresge PO silent 9 days",
    body: "No reply from Sarah on the data infra app. Last contact Apr 22. Decision window narrowing.",
    cta: "Draft email",
  },
  {
    id: "an3",
    level: "info",
    title: "Federal pipeline 2.4× larger than Q1",
    body: "Three federal apps in flight ($1.49M unweighted). Worth confirming match capacity with finance.",
    cta: "Open thread",
  },
]
