import type { Grant, TeamMember, ActionItem, Anomaly, Stage } from "./types"

export const team: TeamMember[] = [
  { id: "maria", name: "Maria Chen", initials: "MC", role: "Grants Manager", load: 142, color: "#5A56B3" },
  { id: "elizabeth", name: "Elizabeth Ward", initials: "EW", role: "Grants Manager", load: 96, color: "#6366F1" },
  { id: "laurie", name: "Laurie Park", initials: "LP", role: "Research Lead", load: 64, color: "#10B981" },
  { id: "grace", name: "Grace Okafor", initials: "GO", role: "Writer", load: 88, color: "#F59E0B" },
  { id: "nina", name: "Nina Alvarez", initials: "NA", role: "Programs Lead", load: 71, color: "#06B6D4" },
  { id: "james", name: "James Wu", initials: "JW", role: "ED", load: 38, color: "#0F3E17" },
  { id: "unassigned", name: "Unassigned", initials: "?", role: "Pool", load: 0, color: "#94A3B8" },
]

export const stageOrder: Stage[] = [
  "Researching",
  "Planned",
  "LOI In Progress",
  "LOI Submitted",
  "Application In Progress",
  "Application Submitted",
  "Awarded - Active",
  "Closed",
  "Declined",
]

export const grants: Grant[] = [
  {
    id: "G-2024-118",
    title: "Diabetes Prevention Program · Year 2",
    funder: "HHS / HRSA",
    funderType: "Federal",
    stage: "Awarded - Active",
    nextAction: "Q2 drawdown package",
    deadline: "2026-05-15",
    daysToDeadline: 14,
    award: 487500,
    weighted: 487500,
    ownerId: "elizabeth",
    cycle: "Y2",
    fundingSource: "HRSA-23-104",
    cfda: "93.426",
    fain: "U58DP007214",
    period: "09/01/24 — 08/31/25",
    indirect: 0.155,
    matchRequired: true,
    lastUpdated: "2 hours ago",
    projectGroup: "Health Equity",
    priority: "P0",
    renewalLikelihood: "High",
    serviceArea:
      "Springfield, Hartford, and New Britain — six FQHC sites plus two mobile outreach units (MA / CT border communities)",
    geography: "Springfield, MA (prime applicant) · clinical sites in MA & CT",
    programSummary:
      "Year 2 of HRSA’s Diabetes Prevention Program scales lifestyle coaching for adults at elevated risk for type 2 diabetes. The cohort prioritizes Medicaid-heavy panels, language access (English / Spanish / Portuguese), and warm handoffs from ED and community health worker programs. This workspace tracks drawdowns against the federal cost objective, match from hospital partners, and mid-year reporting that now includes new equity metrics from the March template. Finance, programs, and grants stay aligned on Hartford vs. Springfield personnel splits and indirect so reimbursement packets clear without rework.",
    opportunityLocation:
      "Springfield Clinical Consortium — legal applicant in Springfield, MA; finance and grants office of record at the consortium HQ.",
    projectLocation:
      "Six FQHC delivery sites in Springfield, Hartford, and New Britain plus two mobile units; see NOFO site table and HRSA-approved scope of work.",
    residencyLocation:
      "No residency requirement for participants; program staff must meet HRSA credentialing at assigned sites (MA / CT).",
    irs990Snapshot:
      "Federal pass-through — funder 990-PF not applicable. Track prime A-133 / Uniform Guidance single audit threshold and subrecipient risk tiers on file with OIG exclusions check (demo).",
    ineligibility:
      "Individuals (except as enrolled participants), for-profit clinical entities as prime without waiver, duplicate HRSA DPP awards for overlapping cohorts, costs outside approved budget period, and lobbying with federal funds.",
    opportunityCompliance:
      "Single Audit / Uniform Guidance applies above threshold. Subrecipient agreements must flow down EDGAR clauses. Advocacy and legislative activity cannot be charged to this award (demo).",
    opportunityEligibleApplicants: [
      "501(c)(3) nonprofit prime applicants",
      "State, territorial, or local governmental entities (as pass-through)",
      "Federally recognized Tribal organizations (with statutory eligibility)",
    ],
    ineligibilityBullets: [
      "Individuals or sole proprietorships as prime",
      "For-profit clinical entities as prime without waiver",
      "Duplicate HRSA awards for overlapping cohort populations",
      "Costs outside the approved budget period or scope",
    ],
  },
  {
    id: "G-2025-042",
    title: "Community Health Workers Initiative",
    funder: "Robert Wood Johnson Foundation",
    funderType: "Private",
    stage: "LOI In Progress",
    nextAction: "Finalize LOI narrative",
    deadline: "2026-05-08",
    daysToDeadline: 7,
    award: 250000,
    weighted: 87500,
    ownerId: "grace",
    cycle: "2025",
    fundingSource: "Pioneering Ideas",
    period: "01/01/26 — 12/31/27",
    lastUpdated: "yesterday",
    projectGroup: "Workforce",
    priority: "P1",
    renewalLikelihood: "Medium",
    serviceArea: "Boston, Lawrence, and Brockton — CHW placements with health centers and housing agencies",
    geography: "Boston, MA (applicant) · satellite coordination in Lawrence",
    programSummary:
      "Robert Wood Johnson’s Pioneering Ideas track supports community health workers bridging clinical care and social needs. The proposal ties CHW tenure to wage progression, supervision ladders, and Medicaid billing readiness. Leadership wants the LOI to foreground equity outcomes (housing stability, ED return visits) without over-committing on evaluation design before the July technical workshop.",
    opportunityLocation:
      "Community Care Collaborative — nonprofit applicant; legal domicile and board in Boston, MA.",
    projectLocation:
      "CHW placements with partner FQHCs and housing agencies in Boston, Lawrence, and Brockton; employer sites named in attachment B.",
    residencyLocation:
      "CHWs must live or work within 45 miles of assigned hub (Boston or Lawrence) for on-call coverage; not a clinical residency program.",
    irs990Snapshot:
      "Latest RWJF 990-PF (demo): total assets ~$12.4B · total grants paid ~$500M · median workforce grant ~$350k · no material related-party transactions flagged for this program line.",
    irs990Metrics: [
      { label: "Total assets", value: "~$12.4B" },
      { label: "Grants paid (FY)", value: "~$500M" },
      { label: "Median grant", value: "~$350K" },
      { label: "Payout (approx.)", value: "5.1%" },
    ],
    ineligibility:
      "Direct grants to individuals, for-profit employers as lead applicant, capital campaigns, endowment, debt retirement, and activities outside US public health scope.",
    opportunityCompliance:
      "501(c)(3) public charity status required. Lobbying limited; 501(h) election on file. No RWJF funds for ballot measure work. Indirect capped per RWJF budget template (demo).",
    opportunityPriorityAreas: [
      "Community health worker tenure and supervision",
      "Medicaid readiness and billing integrity",
      "Housing stability and ED utilization outcomes",
      "Language access and culturally competent care",
      "Employer and FQHC partnership depth",
    ],
    opportunityFundingUses: ["Program staffing", "Training & certification", "Data systems", "Partner subawards"],
    opportunityEligibleApplicants: [
      "501(c)(3) public charities",
      "Local or regional government partners (as subrecipient)",
      "Tribal health organizations (with documented partnership)",
    ],
    ineligibilityBullets: [
      "Direct grants to individuals",
      "For-profit employers as lead applicant",
      "Capital campaigns, endowment, or debt retirement",
      "Activities outside US public health scope",
    ],
    irs990GivingTrend: [
      { year: 2018, amount: 5.2 },
      { year: 2019, amount: 5.8 },
      { year: 2020, amount: 6.5 },
      { year: 2021, amount: 7.8 },
      { year: 2022, amount: 8.2 },
    ],
  },
  {
    id: "G-2025-043",
    title: "General Operating Support · 2025",
    funder: "Hartford Foundation",
    funderType: "Private",
    stage: "LOI In Progress",
    nextAction: "Send LOI to Hartford PO",
    deadline: "2026-05-12",
    daysToDeadline: 11,
    award: 150000,
    weighted: 67500,
    ownerId: "elizabeth",
    cycle: "2025",
    fundingSource: "Greater Hartford Grants",
    period: "07/01/25 — 06/30/26",
    lastUpdated: "3 hours ago",
    projectGroup: "General Op",
    priority: "P1",
    renewalLikelihood: "High",
    serviceArea: "Capital region — arts, youth development, and neighborhood stabilization grantees",
    geography: "Hartford, CT (HQ)",
    programSummary:
      "General operating support keeps backbone staffing for pooled learning, cohort facilitation, and shared measurement. Hartford’s PO asked for clearer cash-flow narrative after last year’s one-time capital grant; this cycle emphasizes 18-month runway, reserve policy, and how GOS strengthens partner sub-grants.",
  },
  {
    id: "G-2025-044",
    title: "Skoll Award · Systems Change Cohort",
    funder: "Skoll Foundation",
    funderType: "Private",
    stage: "Researching",
    nextAction: "Warm intro from board chair",
    deadline: "2026-06-30",
    daysToDeadline: 60,
    award: 1250000,
    weighted: 125000,
    ownerId: "nina",
    cycle: "2025",
    fundingSource: "Open Call",
    lastUpdated: "5 days ago",
    projectGroup: "Health Equity",
    priority: "P2",
    renewalLikelihood: "Unknown",
    serviceArea: "US + select global south pilot communities (systems-change narrative)",
    geography: "Remote-first team · board anchor in New York, NY",
    programSummary:
      "Skoll’s systems-change cohort looks for leverage on economic mobility and climate justice intersections. We are still validating whether our operating model fits their theory of change vs. a program-restricted ask. Research stage work is focused on comparable awards, governance expectations, and how much co-funding Skoll typically expects before first site visit.",
  },
  {
    id: "G-2025-045",
    title: "Workforce Capacity Grant · Cohort 3",
    funder: "Cummings Foundation",
    funderType: "Private",
    stage: "LOI In Progress",
    nextAction: "Reassign — Maria over capacity",
    deadline: "2026-05-20",
    daysToDeadline: 19,
    award: 100000,
    weighted: 35000,
    ownerId: "maria",
    cycle: "2025",
    fundingSource: "$100K for 100 grants",
    period: "10/01/25 — 09/30/26",
    lastUpdated: "1 day ago",
    projectGroup: "Workforce",
    priority: "P2",
    renewalLikelihood: "Low",
    flagged: true,
  },
  {
    id: "G-2025-046",
    title: "Rural Health Telehealth Expansion",
    funder: "USDA Rural Development",
    funderType: "Federal",
    stage: "Application In Progress",
    nextAction: "Budget narrative draft",
    deadline: "2026-05-30",
    daysToDeadline: 29,
    award: 425000,
    weighted: 233750,
    ownerId: "laurie",
    cycle: "FY26",
    fundingSource: "RHCD-26-001",
    cfda: "10.855",
    period: "10/01/26 — 09/30/29",
    indirect: 0.1,
    matchRequired: true,
    lastUpdated: "today",
    projectGroup: "Health Equity",
    priority: "P1",
    renewalLikelihood: "Unknown",
  },
  {
    id: "G-2025-047",
    title: "Mental Health First Aid Training",
    funder: "SAMHSA",
    funderType: "Federal",
    stage: "Application In Progress",
    nextAction: "Logic model review",
    deadline: "2026-06-05",
    daysToDeadline: 35,
    award: 320000,
    weighted: 176000,
    ownerId: "grace",
    cycle: "FY26",
    fundingSource: "SM-26-014",
    cfda: "93.243",
    period: "09/30/26 — 09/29/29",
    matchRequired: false,
    lastUpdated: "4 hours ago",
    projectGroup: "Capacity",
    priority: "P1",
    renewalLikelihood: "Medium",
    blocked: true,
    blockedReason: "Awaiting CFO budget sign-off",
  },
  {
    id: "G-2025-048",
    title: "Youth Substance Use Prevention",
    funder: "Conrad Hilton Foundation",
    funderType: "Private",
    stage: "Application In Progress",
    nextAction: "Outcomes framework",
    deadline: "2026-06-10",
    daysToDeadline: 40,
    award: 200000,
    weighted: 110000,
    ownerId: "nina",
    cycle: "2026",
    fundingSource: "Catholic Sisters Initiative",
    lastUpdated: "yesterday",
    projectGroup: "Health Equity",
    priority: "P2",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-049",
    title: "Data Infrastructure Modernization",
    funder: "Kresge Foundation",
    funderType: "Private",
    stage: "Application In Progress",
    nextAction: "Tech narrative + vendor quotes",
    deadline: "2026-05-25",
    daysToDeadline: 24,
    award: 350000,
    weighted: 192500,
    ownerId: "maria",
    cycle: "2026",
    fundingSource: "Human Services Program",
    lastUpdated: "6 days ago",
    projectGroup: "Capacity",
    priority: "P2",
    renewalLikelihood: "Low",
    flagged: true,
  },
  {
    id: "G-2025-050",
    title: "Healthcare Access Fellowship",
    funder: "Kellogg Foundation",
    funderType: "Private",
    stage: "Application In Progress",
    nextAction: "Letters of support",
    deadline: "2026-06-15",
    daysToDeadline: 45,
    award: 175000,
    weighted: 96250,
    ownerId: "laurie",
    cycle: "2026",
    fundingSource: "Racial Equity Program",
    lastUpdated: "today",
    projectGroup: "Workforce",
    priority: "P3",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-051",
    title: "Maternal Health Outcomes Research",
    funder: "NIH / NICHD",
    funderType: "Federal",
    stage: "Application Submitted",
    nextAction: "Awaiting study section review",
    deadline: "2026-08-01",
    daysToDeadline: 90,
    award: 740000,
    weighted: 296000,
    ownerId: "laurie",
    cycle: "FY26",
    fundingSource: "R01 Mechanism",
    cfda: "93.865",
    period: "12/01/26 — 11/30/29",
    matchRequired: false,
    lastUpdated: "2 weeks ago",
    projectGroup: "Research",
    priority: "P2",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-052",
    title: "Community Mental Health Block Grant",
    funder: "CT Dept of Health",
    funderType: "State",
    stage: "Application Submitted",
    nextAction: "Site visit scheduled",
    deadline: "2026-06-20",
    daysToDeadline: 50,
    award: 215000,
    weighted: 86000,
    ownerId: "nina",
    cycle: "FY26",
    fundingSource: "MHBG Pass-through",
    period: "07/01/26 — 06/30/27",
    lastUpdated: "1 week ago",
    projectGroup: "Health Equity",
    priority: "P3",
    renewalLikelihood: "High",
  },
  {
    id: "G-2024-088",
    title: "School-Based Health Centers · Year 3",
    funder: "HHS / HRSA",
    funderType: "Federal",
    stage: "Awarded - Active",
    nextAction: "Mid-year progress report",
    deadline: "2026-05-31",
    daysToDeadline: 30,
    award: 612000,
    weighted: 612000,
    ownerId: "maria",
    cycle: "Y3",
    fundingSource: "HRSA-22-088",
    cfda: "93.224",
    fain: "H80CS00214",
    period: "06/01/24 — 05/31/25",
    indirect: 0.155,
    matchRequired: true,
    lastUpdated: "today",
    projectGroup: "Health Equity",
    priority: "P0",
    renewalLikelihood: "High",
  },
  {
    id: "G-2024-091",
    title: "Health Equity Innovation Fund",
    funder: "California Endowment",
    funderType: "Private",
    stage: "Awarded - Active",
    nextAction: "Q1 narrative report",
    deadline: "2026-05-20",
    daysToDeadline: 19,
    award: 300000,
    weighted: 300000,
    ownerId: "grace",
    cycle: "Y1",
    fundingSource: "Building Healthy Communities",
    period: "04/01/25 — 03/31/26",
    lastUpdated: "yesterday",
    projectGroup: "Health Equity",
    priority: "P1",
    renewalLikelihood: "High",
    flagged: true,
  },
  {
    id: "G-2024-095",
    title: "Workforce Training Pipeline",
    funder: "Department of Labor",
    funderType: "Federal",
    stage: "Awarded - Active",
    nextAction: "PMS drawdown",
    deadline: "2026-06-01",
    daysToDeadline: 31,
    award: 540000,
    weighted: 540000,
    ownerId: "james",
    cycle: "Y1",
    fundingSource: "WIOA Grant",
    cfda: "17.258",
    fain: "DOL-2024-WIOA-0042",
    period: "07/01/24 — 06/30/26",
    indirect: 0.12,
    matchRequired: true,
    lastUpdated: "3 days ago",
    projectGroup: "Workforce",
    priority: "P0",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-053",
    title: "Community Resilience Initiative",
    funder: "MacArthur Foundation",
    funderType: "Private",
    stage: "Researching",
    nextAction: "Review eligibility criteria",
    deadline: "2026-07-15",
    daysToDeadline: 75,
    award: 600000,
    weighted: 60000,
    ownerId: "laurie",
    cycle: "2026",
    fundingSource: "100&Change",
    lastUpdated: "today",
    projectGroup: "Health Equity",
    priority: "P3",
    renewalLikelihood: "Unknown",
  },
  {
    id: "G-2025-054",
    title: "Digital Health Equity Toolkit",
    funder: "Walton Family Foundation",
    funderType: "Private",
    stage: "Researching",
    nextAction: "Concept memo",
    deadline: "2026-08-30",
    daysToDeadline: 120,
    award: 225000,
    weighted: 22500,
    ownerId: "grace",
    cycle: "2026",
    fundingSource: "Education / K-12",
    lastUpdated: "1 week ago",
    projectGroup: "Capacity",
    priority: "P3",
    renewalLikelihood: "Unknown",
  },
  {
    id: "G-2024-076",
    title: "Behavioral Health Integration · Y2",
    funder: "BCBS Foundation",
    funderType: "Corporate",
    stage: "Awarded - Active",
    nextAction: "Annual report",
    deadline: "2026-07-01",
    daysToDeadline: 60,
    award: 175000,
    weighted: 175000,
    ownerId: "nina",
    cycle: "Y2",
    fundingSource: "Health Equity Program",
    period: "07/01/24 — 06/30/26",
    lastUpdated: "5 days ago",
    projectGroup: "Health Equity",
    priority: "P2",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-055",
    title: "Telehealth Equipment Upgrade",
    funder: "Verizon Foundation",
    funderType: "Corporate",
    stage: "Planned",
    nextAction: "Decide on go/no-go",
    deadline: "2026-06-25",
    daysToDeadline: 55,
    award: 75000,
    weighted: 18750,
    ownerId: "james",
    cycle: "2026",
    fundingSource: "Digital Inclusion",
    lastUpdated: "yesterday",
    projectGroup: "Capacity",
    priority: "P3",
    renewalLikelihood: "Low",
  },
  {
    id: "G-2025-056",
    title: "Substance Use Recovery Pilot",
    funder: "City of Hartford",
    funderType: "Local",
    stage: "LOI In Progress",
    nextAction: "Coordinate with city liaison",
    deadline: "2026-05-18",
    daysToDeadline: 17,
    award: 50000,
    weighted: 22500,
    ownerId: "nina",
    cycle: "FY26",
    fundingSource: "ARPA Set-aside",
    period: "07/01/26 — 06/30/27",
    lastUpdated: "today",
    projectGroup: "Health Equity",
    priority: "P2",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2025-057",
    title: "Youth Leadership Development",
    funder: "United Way of CT",
    funderType: "Private",
    stage: "Application Submitted",
    nextAction: "Awaiting decision",
    deadline: "2026-07-30",
    daysToDeadline: 90,
    award: 85000,
    weighted: 38250,
    ownerId: "grace",
    cycle: "2026",
    fundingSource: "Community Impact Fund",
    period: "01/01/27 — 12/31/27",
    lastUpdated: "2 weeks ago",
    projectGroup: "Workforce",
    priority: "P3",
    renewalLikelihood: "Medium",
  },
  /** --- Closed / declined — realistic pursuit value + reasons (KPI “lost” lane) --- */
  {
    id: "G-2024-061",
    title: "Rural Residency Pathway (R21 feasibility)",
    funder: "NIH / NIMHD",
    funderType: "Federal",
    stage: "Declined",
    nextAction: "Declined — impact score below payline (32nd %ile)",
    deadline: "2025-11-18",
    daysToDeadline: 999,
    award: 418000,
    weighted: 0,
    ownerId: "laurie",
    cycle: "FY25",
    fundingSource: "R21 Exploratory",
    cfda: "93.307",
    period: "12/01/25 — 11/30/27",
    matchRequired: false,
    lastUpdated: "3 months ago",
    projectGroup: "Workforce",
    priority: "P2",
    renewalLikelihood: "Unknown",
  },
  {
    id: "G-2024-062",
    title: "Associate Health Program · Community Grants",
    funder: "Walmart Foundation",
    funderType: "Corporate",
    stage: "Closed",
    nextAction: "Closed — org withdrew after HQ strategy shift (Q3)",
    deadline: "2025-09-30",
    daysToDeadline: 999,
    award: 165000,
    weighted: 0,
    ownerId: "james",
    cycle: "FY25",
    fundingSource: "State Giving",
    period: "01/01/26 — 12/31/26",
    lastUpdated: "4 months ago",
    projectGroup: "Health Equity",
    priority: "P3",
    renewalLikelihood: "Low",
  },
  {
    id: "G-2025-031",
    title: "Strategic Prevention Framework – Local",
    funder: "SAMHSA",
    funderType: "Federal",
    stage: "Declined",
    nextAction: "Not recommended — peer review noted budget staffing gap",
    deadline: "2025-12-01",
    daysToDeadline: 999,
    award: 287500,
    weighted: 0,
    ownerId: "grace",
    cycle: "FY26",
    fundingSource: "SPF-R",
    cfda: "93.243",
    period: "09/30/26 — 09/29/29",
    lastUpdated: "5 months ago",
    projectGroup: "Health Equity",
    priority: "P2",
    renewalLikelihood: "Unknown",
  },
  {
    id: "G-2024-063",
    title: "Neighborhood Safety Mini-Grants (duplicate file)",
    funder: "City of Hartford",
    funderType: "Local",
    stage: "Closed",
    nextAction: "Consolidated under G-2025-056 — solicitation closed",
    deadline: "2025-08-15",
    daysToDeadline: 999,
    award: 47500,
    weighted: 0,
    ownerId: "nina",
    cycle: "FY25",
    fundingSource: "ARPA Set-aside",
    period: "07/01/25 — 06/30/26",
    lastUpdated: "6 months ago",
    projectGroup: "Health Equity",
    priority: "P3",
    renewalLikelihood: "Low",
  },
  {
    id: "G-2024-064",
    title: "Integrated Care Innovation Fund",
    funder: "CT Dept of Social Services",
    funderType: "State",
    stage: "Declined",
    nextAction: "State panel — not selected (rank 14 of 42)",
    deadline: "2025-10-22",
    daysToDeadline: 999,
    award: 512000,
    weighted: 0,
    ownerId: "maria",
    cycle: "FY26",
    fundingSource: "1115 Waiver reinvestment",
    period: "07/01/26 — 06/30/28",
    matchRequired: true,
    lastUpdated: "7 months ago",
    projectGroup: "Health Equity",
    priority: "P1",
    renewalLikelihood: "Unknown",
  },
  {
    id: "G-2025-032",
    title: "Pandemic Learning Recovery · District Partnership",
    funder: "Bill & Melinda Gates Foundation",
    funderType: "Private",
    stage: "Declined",
    nextAction: "Declined at LOI — geography outside current portfolio focus",
    deadline: "2026-01-12",
    daysToDeadline: 999,
    award: 725000,
    weighted: 0,
    ownerId: "nina",
    cycle: "2026",
    fundingSource: "K-12 Networks",
    period: "07/01/26 — 06/30/29",
    lastUpdated: "last month",
    projectGroup: "Capacity",
    priority: "P2",
    renewalLikelihood: "Unknown",
    flagged: true,
  },
  {
    id: "G-2026-RAC1",
    title: "After-School Literacy Pilot · Block Grant",
    funder: "Racine Community Foundation",
    funderType: "Local",
    stage: "Awarded - Active",
    nextAction: "Accelerate draw schedule to correct underspend pace",
    deadline: "2026-12-15",
    daysToDeadline: 223,
    award: 185000,
    weighted: 185000,
    ownerId: "elizabeth",
    cycle: "2026",
    fundingSource: "Community Impact — Youth Education",
    period: "01/01/26 — 12/31/26",
    lastUpdated: "today",
    projectGroup: "Capacity",
    priority: "P1",
    renewalLikelihood: "Medium",
    flagged: true,
  },
  {
    id: "G-2026-SKW",
    title: "Wetlands & Watershed Restoration",
    funder: "Skoll Foundation",
    funderType: "Private",
    stage: "Application In Progress",
    nextAction: "Submit full proposal package",
    deadline: "2026-05-05",
    daysToDeadline: -1,
    award: 850000,
    weighted: 340000,
    ownerId: "laurie",
    cycle: "2026",
    fundingSource: "Environmental Systems Change",
    period: "07/01/26 — 06/30/29",
    lastUpdated: "yesterday",
    projectGroup: "Capacity",
    priority: "P1",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2026-HEW",
    title: "Hewlett Climate Resilience & Energy Transition",
    funder: "William and Flora Hewlett Foundation",
    funderType: "Private",
    stage: "Awarded - Active",
    nextAction: "Mid-year narrative and metrics workbook",
    deadline: "2026-05-15",
    daysToDeadline: 9,
    award: 420000,
    weighted: 420000,
    ownerId: "elizabeth",
    cycle: "2026",
    fundingSource: "Climate Initiative",
    period: "01/01/26 — 12/31/28",
    lastUpdated: "today",
    projectGroup: "Capacity",
    priority: "P1",
    renewalLikelihood: "High",
  },
  {
    id: "G-2026-HFFI",
    title: "Healthy Food Financing · CDFI Corridor",
    funder: "USDA / Treasury (HFFI)",
    funderType: "Federal",
    stage: "Awarded - Active",
    nextAction: "Reconcile draw vs obligated ceiling",
    deadline: "2026-06-30",
    daysToDeadline: 55,
    award: 750000,
    weighted: 750000,
    ownerId: "elizabeth",
    cycle: "FY26",
    fundingSource: "America's Healthy Food Financing Initiative",
    period: "10/01/25 — 09/30/28",
    lastUpdated: "today",
    projectGroup: "Health Equity",
    priority: "P0",
    renewalLikelihood: "High",
    flagged: true,
  },
  {
    id: "G-2026-CPT",
    title: "General Program Support",
    funder: "CenterPoint Energy Foundation",
    funderType: "Corporate",
    stage: "Awarded - Active",
    nextAction: "Complete accounting system tie-out",
    deadline: "2026-08-01",
    daysToDeadline: 87,
    award: 275000,
    weighted: 275000,
    ownerId: "elizabeth",
    cycle: "2026",
    fundingSource: "Charitable Giving",
    period: "01/01/26 — 12/31/26",
    lastUpdated: "3 days ago",
    projectGroup: "General Op",
    priority: "P1",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2026-ONB",
    title: "Neighborhood Investment Fund",
    funder: "Old National Bank",
    funderType: "Corporate",
    stage: "Application In Progress",
    nextAction: "Refresh outcomes narrative and budget notes",
    deadline: "2026-06-01",
    daysToDeadline: 26,
    award: 150000,
    weighted: 105000,
    ownerId: "elizabeth",
    cycle: "2026",
    fundingSource: "Community Development",
    period: "07/01/26 — 06/30/29",
    lastUpdated: "46 days ago",
    projectGroup: "Capacity",
    priority: "P2",
    renewalLikelihood: "Medium",
  },
  {
    id: "G-2026-VER",
    title: "Open RFP (Program Expansion)",
    funder: "Versafund",
    funderType: "Private",
    stage: "Application In Progress",
    nextAction: "Upload final proposal PDF and attestations",
    deadline: "2026-05-03",
    daysToDeadline: -3,
    award: 500000,
    weighted: 200000,
    ownerId: "laurie",
    cycle: "2026",
    fundingSource: "Versafund Grant Program",
    lastUpdated: "today",
    projectGroup: "Capacity",
    priority: "P0",
    renewalLikelihood: "Unknown",
    blocked: true,
    blockedReason: "Full proposal deadline passed — submit or withdraw",
  },
  {
    id: "G-2026-FRY",
    title: "Employment & Economic Mobility",
    funder: "Fry Foundation",
    funderType: "Private",
    stage: "Researching",
    nextAction: "Confirm lead program officer and internal owner",
    deadline: "2026-07-15",
    daysToDeadline: 70,
    award: 180000,
    weighted: 54000,
    ownerId: "unassigned",
    cycle: "2026",
    fundingSource: "Employment Grant",
    lastUpdated: "5 days ago",
    projectGroup: "Workforce",
    priority: "P2",
    renewalLikelihood: "Unknown",
  },
]

/** Prototype grant id for Racine underspend Q&A + `mixalt://grant/...` from chat */
export const RACINE_COMMUNITY_FOUNDATION_GRANT_ID = "G-2026-RAC1" as const

export const actionQueue: ActionItem[] = [
  {
    id: "mw-skoll",
    issueCategory: "upcoming",
    itemLabel: "Full proposal deadline",
    detail: "Due May 5: confirm sign-offs, then upload.",
    grantTitle: "Wetlands & Watershed Restoration · Skoll",
    grantId: "G-2026-SKW",
    issueKind: "deadline",
    severity: "high",
    highlightFieldKey: "full_proposal_deadline",
    highlightFieldLabel: "Full proposal deadline",
    highlightReason: "Submission window closes May 5 — package still in final QA",
    stage: "Application In Progress",
    due: "May 5",
    daysOut: 0,
    ownerId: "laurie",
    lastUpdatedDisplay: "5/5/2026",
    ctaLabel: "Open submission",
  },
  {
    id: "mw-hewlett",
    issueCategory: "upcoming",
    itemLabel: "Task — Report",
    detail:
      "Report due May 15: finalize workbook and narrative.",
    grantTitle: "Hewlett Climate Resilience & Energy Transition",
    grantId: "G-2026-HEW",
    issueKind: "reporting",
    severity: "medium",
    highlightFieldKey: "full_proposal_deadline",
    highlightFieldLabel: "Report deadline",
    highlightReason: "Mid-year report due May 15 — workbook and narrative not yet consolidated",
    stage: "Awarded - Active",
    due: "May 15",
    daysOut: 9,
    ownerId: "elizabeth",
    lastUpdatedDisplay: "5/4/2026",
    ctaLabel: "Open report workspace",
  },
  {
    id: "mw-racine",
    issueCategory: "spend",
    itemLabel: "Under-spend",
    detail: "Award is pacing about $25K under plan.",
    grantTitle: "After-School Literacy Pilot · Block Grant",
    grantId: "G-2026-RAC1",
    issueKind: "financial",
    severity: "high",
    highlightFieldKey: "budget_spend",
    highlightFieldLabel: "Budget vs actuals",
    highlightReason: "Spend tracking ~$25K under plan — correction needed before next monitoring check-in",
    stage: "Awarded - Active",
    due: "This month",
    daysOut: 14,
    ownerId: "elizabeth",
    lastUpdatedDisplay: "5/6/2026",
    ctaLabel: "Review burn chart",
  },
  {
    id: "mw-hffi",
    issueCategory: "spend",
    itemLabel: "Over-spend",
    detail: "HFFI spend runs roughly $50K over budget.",
    grantTitle: "Healthy Food Financing · CDFI Corridor",
    grantId: "G-2026-HFFI",
    issueKind: "financial",
    severity: "high",
    highlightFieldKey: "budget_spend",
    highlightFieldLabel: "Budget vs actuals",
    highlightReason: "Spend ~$50K over plan — needs finance and PO alignment",
    stage: "Awarded - Active",
    due: "This week",
    daysOut: 5,
    ownerId: "elizabeth",
    lastUpdatedDisplay: "5/6/2026",
    ctaLabel: "Open variance",
  },
  {
    id: "mw-centerpoint",
    issueCategory: "setup",
    itemLabel: "Accounting integration",
    detail: "Manual GL bridge blocks clean month-end reporting.",
    grantTitle: "CenterPoint Foundation · General Program Support",
    grantId: "G-2026-CPT",
    issueKind: "ops",
    severity: "medium",
    highlightFieldKey: "integration_status",
    highlightFieldLabel: "Accounting integration",
    highlightReason: "ERP / grant module mapping unfinished — blocks clean close",
    stage: "Awarded - Active",
    due: "Next week",
    daysOut: 7,
    ownerId: "elizabeth",
    lastUpdatedDisplay: "5/2/2026",
    ctaLabel: "Finish setup",
  },
  {
    id: "mw-oldnational",
    issueCategory: "inactive",
    itemLabel: "Activity",
    detail: "Forty-six days silent; schedule program officer touchpoint.",
    grantTitle: "Old National Bank · Neighborhood Investment Fund",
    grantId: "G-2026-ONB",
    issueKind: "relationship",
    severity: "medium",
    highlightFieldKey: "integration_status",
    highlightFieldLabel: "Activity log",
    highlightReason: "46 days without material progress — relationship cooling",
    stage: "Application In Progress",
    due: "Stale",
    daysOut: 46,
    ownerId: "elizabeth",
    lastUpdatedDisplay: "3/21/2026",
    ctaLabel: "Log next step",
  },
  {
    id: "mw-versafund",
    issueCategory: "overdue",
    itemLabel: "Full proposal deadline",
    detail: "Three days past deadline: extend, withdraw, or late-file.",
    grantTitle: "Versafund · Open RFP (Program Expansion)",
    grantId: "G-2026-VER",
    issueKind: "deadline",
    severity: "critical",
    highlightFieldKey: "full_proposal_deadline",
    highlightFieldLabel: "Full proposal deadline",
    highlightReason: "Deadline missed by 3 days — escalation required",
    stage: "Application In Progress",
    due: "May 3",
    daysOut: -3,
    ownerId: "laurie",
    lastUpdatedDisplay: "5/6/2026",
    ctaLabel: "Resolve deadline",
  },
  {
    id: "mw-fry",
    issueCategory: "missing_data",
    itemLabel: "Owner",
    detail: "No owner assigned; routing and reminders fall through.",
    grantTitle: "Fry Foundation · Employment & Economic Mobility",
    grantId: "G-2026-FRY",
    issueKind: "missing_data",
    severity: "medium",
    highlightFieldKey: "owner",
    highlightFieldLabel: "Grant owner",
    highlightReason: "Owner field blank — work queue cannot assign accountability",
    stage: "Researching",
    due: "When free",
    daysOut: 10,
    ownerId: "unassigned",
    lastUpdatedDisplay: "5/1/2026",
    ctaLabel: "Assign owner",
  },
]

export const anomalies: Anomaly[] = [
  {
    id: "an1",
    level: "crit",
    title: "Hartford burn 18% over plan",
    body: "DPP Y2 personnel spend is tracking 18% ahead of plan through Q2 — risks running out before Sept.",
    cta: "Investigate",
  },
  {
    id: "an2",
    level: "warn",
    title: "Kresge PO silent 9 days",
    body: "No reply from Sarah on the data infra app. Last contact Apr 22. Decision window narrowing.",
    cta: "Draft email",
  },
  {
    id: "an3",
    level: "info",
    title: "Federal pipeline 2.4× larger than Q1",
    body: "Three federal apps in flight ($1.49M unweighted). Worth confirming match capacity with finance.",
    cta: "Open thread",
  },
]
